#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ceph
Version  : 12.0.3
Release  : 38
URL      : http://download.ceph.com/tarballs/ceph_12.0.3.orig.tar.gz
Source0  : http://download.ceph.com/tarballs/ceph_12.0.3.orig.tar.gz
Source1  : ceph.tmpfiles
Summary  : Ceph Base Package
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 CC-BY-SA-1.0 GPL-2.0 GPL-2.0-with-autoconf-exception LGPL-2.0 LGPL-2.1 MIT MTLL NTP
Requires: pecan
Requires: requests
Requires: setuptools
BuildRequires : Cython
BuildRequires : Sphinx-python
BuildRequires : boost-dev
BuildRequires : bzip2-dev
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : expat-dev
BuildRequires : fcgi-dev
BuildRequires : googletest
BuildRequires : googletest-dev
BuildRequires : gperftools
BuildRequires : gperftools-dev
BuildRequires : imagesize
BuildRequires : isa-l-dev
BuildRequires : keyutils-dev
BuildRequires : leveldb-dev
BuildRequires : libaio-dev
BuildRequires : libatomic_ops-dev
BuildRequires : lz4-dev
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pecan
BuildRequires : pip
BuildRequires : pkgconfig(nss)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : requests
BuildRequires : scons
BuildRequires : sed
BuildRequires : setuptools
BuildRequires : snappy-dev
BuildRequires : systemd-dev
BuildRequires : tox
BuildRequires : tox-python
BuildRequires : util-linux-dev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : virtualenv
BuildRequires : xfsprogs-dev
BuildRequires : yasm
BuildRequires : zlib-dev
Patch1: 0001-Ceph-sudoers-entry.patch
Patch2: 0001-detect-clearlinux-init-system.patch
Patch3: 0001-Call-ceph-osd-prestart.sh-from-libexec-dir.patch
Patch4: 0001-systemd.patch
Patch5: 0001-bash-completion.patch
Patch6: 0001-os-release.patch

%description
Ceph is a massively scalable, open-source, distributed storage system that runs
on commodity hardware and delivers object, block and file system storage.

%prep
%setup -q -n ceph-12.0.3
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1495113485
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DWITH_LTTNG=OFF -DWITH_FUSE=OFF -DWITH_SYSTEMD=ON -DWITH_MGR=OFF -DWITH_PYTHON3=ON -DWITH_TESTS=OFF -DHAVE_BABELTRACE=OFF
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1495113485
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/ceph.conf
## make_install_append content
install -d -m 750 %{buildroot}/usr/share/defaults/sudo/sudoers.d
install -p -D -m 440 ceph.sudoers %{buildroot}/usr/share/defaults/sudo/sudoers.d/ceph
install -d -m 755 %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/50-rbd.rules %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/60-ceph-by-parttypeuuid.rules %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/95-ceph-osd.rules %{buildroot}/usr/lib/udev/rules.d
rm -rf %{buildroot}/usr/etc
## make_install_append end

%files
%defattr(-,root,root,-)
