#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ceph
Version  : 13.2.0
Release  : 62
URL      : https://download.ceph.com/tarballs/ceph_13.2.0.orig.tar.gz
Source0  : https://download.ceph.com/tarballs/ceph_13.2.0.orig.tar.gz
Source1  : ceph.tmpfiles
Summary  : Ceph Base Package
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 CC-BY-4.0 CC-BY-SA-3.0 GPL-2.0 LGPL-2.0 LGPL-2.1 MIT MTLL NTP
Requires: ceph-bin
Requires: ceph-python3
Requires: ceph-config
Requires: ceph-lib
Requires: ceph-data
Requires: ceph-license
Requires: ceph-man
Requires: ceph-python
Requires: CUnit
Requires: CUnit-dev
Requires: Werkzeug
Requires: astroid
Requires: attrs
Requires: bcrypt
Requires: cheroot
Requires: cherrypy
Requires: configparser
Requires: coverage
Requires: elasticsearch
Requires: enum34
Requires: funcsigs
Requires: influxdb
Requires: isort
Requires: lazy-object-proxy
Requires: mccabe
Requires: more-itertools
Requires: oath-toolkit
Requires: pbr
Requires: pecan
Requires: pluggy
Requires: portend
Requires: prettytable
Requires: py
Requires: pycodestyle
Requires: pycparser
Requires: pylint
Requires: pytz
Requires: requests
Requires: setuptools
Requires: six
Requires: tempora
Requires: virtualenv
Requires: wrapt
BuildRequires : CUnit
BuildRequires : CUnit-dev
BuildRequires : Cython
BuildRequires : Sphinx-python
BuildRequires : boost-dev
BuildRequires : bzip2-dev
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : expat-dev
BuildRequires : fcgi-dev
BuildRequires : googletest-dev
BuildRequires : gperf
BuildRequires : gperftools-dev
BuildRequires : imagesize
BuildRequires : isa-l-dev
BuildRequires : keyutils-dev
BuildRequires : leveldb-dev
BuildRequires : libaio-dev
BuildRequires : libatomic_ops-dev
BuildRequires : lz4-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : oath-toolkit-dev
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pecan
BuildRequires : pip
BuildRequires : pkgconfig(babeltrace)
BuildRequires : pkgconfig(nss)
BuildRequires : prettytable
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
BuildRequires : requests
BuildRequires : scons
BuildRequires : sed
BuildRequires : setuptools
BuildRequires : snappy-dev
BuildRequires : systemd-dev
BuildRequires : tox
BuildRequires : tox-python
BuildRequires : util-linux-dev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : virtualenv
BuildRequires : xfsprogs-dev
BuildRequires : xmlsec1-dev
BuildRequires : yasm
BuildRequires : zlib-dev
Patch1: 0001-Ceph-sudoers-entry.patch
Patch2: 0002-Add-Clear-Linux-init-detection.patch
Patch3: 0003-Call-ceph-osd-prestart.sh-from-libexec-dir.patch
Patch4: 0004-Update-systemd-install-path.patch
Patch5: 0005-bash-completion.patch
Patch6: 0006-os-release.patch
Patch7: 0007-Remove-Werror.patch
Patch8: 0008-Point-to-oath-library-cmake-variable-during-linking.patch

%description
Ceph is a massively scalable, open-source, distributed storage system that runs
on commodity hardware and delivers object, block and file system storage.

%package bin
Summary: bin components for the ceph package.
Group: Binaries
Requires: ceph-data
Requires: ceph-config
Requires: ceph-license
Requires: ceph-man

%description bin
bin components for the ceph package.


%package config
Summary: config components for the ceph package.
Group: Default

%description config
config components for the ceph package.


%package data
Summary: data components for the ceph package.
Group: Data

%description data
data components for the ceph package.


%package dev
Summary: dev components for the ceph package.
Group: Development
Requires: ceph-lib
Requires: ceph-bin
Requires: ceph-data
Provides: ceph-devel

%description dev
dev components for the ceph package.


%package doc
Summary: doc components for the ceph package.
Group: Documentation
Requires: ceph-man

%description doc
doc components for the ceph package.


%package lib
Summary: lib components for the ceph package.
Group: Libraries
Requires: ceph-data
Requires: ceph-license

%description lib
lib components for the ceph package.


%package license
Summary: license components for the ceph package.
Group: Default

%description license
license components for the ceph package.


%package man
Summary: man components for the ceph package.
Group: Default

%description man
man components for the ceph package.


%package python
Summary: python components for the ceph package.
Group: Default
Requires: ceph-python3

%description python
python components for the ceph package.


%package python3
Summary: python3 components for the ceph package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ceph package.


%prep
%setup -q -n ceph-13.2.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530277628
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DWITH_LTTNG=OFF -DWITH_FUSE=OFF -DWITH_SYSTEMD=ON -DWITH_MGR_DASHBOARD_FRONTEND=OFF -DWITH_PYTHON3=ON -DMGR_PYTHON_VERSION=3 -DWITH_TESTS=OFF -DHAVE_BABELTRACE=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1530277628
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ceph
cp COPYING-LGPL2.1 %{buildroot}/usr/share/doc/ceph/COPYING-LGPL2.1
cp COPYING-GPL2 %{buildroot}/usr/share/doc/ceph/COPYING-GPL2
cp debian/copyright %{buildroot}/usr/share/doc/ceph/debian_copyright
cp src/zstd/LICENSE %{buildroot}/usr/share/doc/ceph/src_zstd_LICENSE
cp src/zstd/COPYING %{buildroot}/usr/share/doc/ceph/src_zstd_COPYING
cp src/zstd/contrib/linux-kernel/COPYING %{buildroot}/usr/share/doc/ceph/src_zstd_contrib_linux-kernel_COPYING
cp src/xxHash/LICENSE %{buildroot}/usr/share/doc/ceph/src_xxHash_LICENSE
cp src/spdk/LICENSE %{buildroot}/usr/share/doc/ceph/src_spdk_LICENSE
cp src/spdk/dpdk/LICENSE.LGPL %{buildroot}/usr/share/doc/ceph/src_spdk_dpdk_LICENSE.LGPL
cp src/spdk/dpdk/LICENSE.GPL %{buildroot}/usr/share/doc/ceph/src_spdk_dpdk_LICENSE.GPL
cp src/spdk/dpdk/drivers/net/qede/LICENSE.qede_pmd %{buildroot}/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_qede_LICENSE.qede_pmd
cp src/spdk/dpdk/drivers/net/enic/LICENSE %{buildroot}/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_enic_LICENSE
cp src/spdk/dpdk/drivers/net/bnx2x/LICENSE.bnx2x_pmd %{buildroot}/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_bnx2x_LICENSE.bnx2x_pmd
cp src/rocksdb/LICENSE.leveldb %{buildroot}/usr/share/doc/ceph/src_rocksdb_LICENSE.leveldb
cp src/rocksdb/LICENSE.Apache %{buildroot}/usr/share/doc/ceph/src_rocksdb_LICENSE.Apache
cp src/rocksdb/COPYING %{buildroot}/usr/share/doc/ceph/src_rocksdb_COPYING
cp src/rocksdb/docs/LICENSE-DOCUMENTATION %{buildroot}/usr/share/doc/ceph/src_rocksdb_docs_LICENSE-DOCUMENTATION
cp src/rapidjson/license.txt %{buildroot}/usr/share/doc/ceph/src_rapidjson_license.txt
cp src/rapidjson/thirdparty/gtest/googletest/LICENSE %{buildroot}/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googletest_LICENSE
cp src/rapidjson/thirdparty/gtest/googlemock/LICENSE %{buildroot}/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googlemock_LICENSE
cp src/rapidjson/thirdparty/gtest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googlemock_scripts_generator_LICENSE
cp src/rapidjson/bin/jsonschema/LICENSE %{buildroot}/usr/share/doc/ceph/src_rapidjson_bin_jsonschema_LICENSE
cp src/isa-l/LICENSE %{buildroot}/usr/share/doc/ceph/src_isa-l_LICENSE
cp src/googletest/googletest/LICENSE %{buildroot}/usr/share/doc/ceph/src_googletest_googletest_LICENSE
cp src/googletest/googlemock/LICENSE %{buildroot}/usr/share/doc/ceph/src_googletest_googlemock_LICENSE
cp src/googletest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/doc/ceph/src_googletest_googlemock_scripts_generator_LICENSE
cp src/erasure-code/jerasure/jerasure/License.txt %{buildroot}/usr/share/doc/ceph/src_erasure-code_jerasure_jerasure_License.txt
cp src/erasure-code/jerasure/jerasure/COPYING %{buildroot}/usr/share/doc/ceph/src_erasure-code_jerasure_jerasure_COPYING
cp src/erasure-code/jerasure/gf-complete/License.txt %{buildroot}/usr/share/doc/ceph/src_erasure-code_jerasure_gf-complete_License.txt
cp src/erasure-code/jerasure/gf-complete/COPYING %{buildroot}/usr/share/doc/ceph/src_erasure-code_jerasure_gf-complete_COPYING
cp src/dmclock/COPYING-LGPL2.1 %{buildroot}/usr/share/doc/ceph/src_dmclock_COPYING-LGPL2.1
cp src/dmclock/COPYING %{buildroot}/usr/share/doc/ceph/src_dmclock_COPYING
cp src/crypto/isa-l/isa-l_crypto/LICENSE %{buildroot}/usr/share/doc/ceph/src_crypto_isa-l_isa-l_crypto_LICENSE
cp src/civetweb/LICENSE.md %{buildroot}/usr/share/doc/ceph/src_civetweb_LICENSE.md
cp src/civetweb/src/third_party/lua-5.1.5/COPYRIGHT %{buildroot}/usr/share/doc/ceph/src_civetweb_src_third_party_lua-5.1.5_COPYRIGHT
cp src/civetweb/src/third_party/duktape-1.8.0/LICENSE.txt %{buildroot}/usr/share/doc/ceph/src_civetweb_src_third_party_duktape-1.8.0_LICENSE.txt
cp src/civetweb/src/third_party/duktape-1.5.2/LICENSE.txt %{buildroot}/usr/share/doc/ceph/src_civetweb_src_third_party_duktape-1.5.2_LICENSE.txt
cp src/blkin/COPYRIGHT %{buildroot}/usr/share/doc/ceph/src_blkin_COPYRIGHT
cp src/boost/LICENSE_1_0.txt %{buildroot}/usr/share/doc/ceph/src_boost_LICENSE_1_0.txt
cp src/boost/tools/build/src/engine/debian/copyright %{buildroot}/usr/share/doc/ceph/src_boost_tools_build_src_engine_debian_copyright
cp src/boost/tools/boostbook/xsl/caramel/LICENSE %{buildroot}/usr/share/doc/ceph/src_boost_tools_boostbook_xsl_caramel_LICENSE
cp src/boost/tools/bcp/licence_info.hpp %{buildroot}/usr/share/doc/ceph/src_boost_tools_bcp_licence_info.hpp
cp src/boost/tools/bcp/licence_info.cpp %{buildroot}/usr/share/doc/ceph/src_boost_tools_bcp_licence_info.cpp
cp src/boost/libs/date_time/xmldoc/license.xml %{buildroot}/usr/share/doc/ceph/src_boost_libs_date_time_xmldoc_license.xml
cp src/boost/libs/beast/LICENSE_1_0.txt %{buildroot}/usr/share/doc/ceph/src_boost_libs_beast_LICENSE_1_0.txt
cp src/boost/libs/beast/test/extern/zlib-1.2.11/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/doc/ceph/src_boost_libs_beast_test_extern_zlib-1.2.11_contrib_dotzlib_LICENSE_1_0.txt
cp src/boost/libs/beast/test/bench/parser/nodejs-parser/LICENSE-MIT %{buildroot}/usr/share/doc/ceph/src_boost_libs_beast_test_bench_parser_nodejs-parser_LICENSE-MIT
cp src/boost/libs/hana/LICENSE.md %{buildroot}/usr/share/doc/ceph/src_boost_libs_hana_LICENSE.md
cp src/boost/libs/hof/LICENSE.md %{buildroot}/usr/share/doc/ceph/src_boost_libs_hof_LICENSE.md
cp src/boost/libs/compute/LICENSE_1_0.txt %{buildroot}/usr/share/doc/ceph/src_boost_libs_compute_LICENSE_1_0.txt
cp src/boost/libs/callable_traits/LICENSE.md %{buildroot}/usr/share/doc/ceph/src_boost_libs_callable_traits_LICENSE.md
cp src/boost/libs/python/LICENSE_1_0.txt %{buildroot}/usr/share/doc/ceph/src_boost_libs_python_LICENSE_1_0.txt
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/ceph.conf
## make_install_append content
install -d -m 750 %{buildroot}/usr/share/defaults/sudo/sudoers.d
install -p -D -m 440 ceph.sudoers %{buildroot}/usr/share/defaults/sudo/sudoers.d/ceph
install -d -m 755 %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/50-rbd.rules %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/60-ceph-by-parttypeuuid.rules %{buildroot}/usr/lib/udev/rules.d
install -p -D -m 644 udev/95-ceph-osd.rules %{buildroot}/usr/lib/udev/rules.d
rm -rf %{buildroot}/usr/etc
rm -rf %{buildroot}/usr/lib/systemd/system/ceph-fuse*
rm -rf %{buildroot}/usr/lib/systemd/system/ceph-mgr*
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/ceph/mgr/CMakeLists.txt
/usr/lib64/ceph/mgr/__pycache__/mgr_module.cpython-36.pyc
/usr/lib64/ceph/mgr/balancer/__init__.py
/usr/lib64/ceph/mgr/balancer/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/balancer/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/balancer/module.py
/usr/lib64/ceph/mgr/dashboard/.coveragerc
/usr/lib64/ceph/mgr/dashboard/.editorconfig
/usr/lib64/ceph/mgr/dashboard/.pylintrc
/usr/lib64/ceph/mgr/dashboard/CMakeLists.txt
/usr/lib64/ceph/mgr/dashboard/HACKING.rst
/usr/lib64/ceph/mgr/dashboard/README.rst
/usr/lib64/ceph/mgr/dashboard/__init__.py
/usr/lib64/ceph/mgr/dashboard/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/awsauth.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/exceptions.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/rest_client.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/settings.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/__pycache__/tools.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/awsauth.py
/usr/lib64/ceph/mgr/dashboard/controllers/__init__.py
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/auth.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/cephfs.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/cluster_configuration.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/dashboard.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/erasure_code_profile.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/host.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/monitor.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/osd.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/perf_counters.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/pool.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/rbd.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/rbd_mirroring.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/rgw.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/summary.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/task.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/__pycache__/tcmu_iscsi.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/controllers/auth.py
/usr/lib64/ceph/mgr/dashboard/controllers/cephfs.py
/usr/lib64/ceph/mgr/dashboard/controllers/cluster_configuration.py
/usr/lib64/ceph/mgr/dashboard/controllers/dashboard.py
/usr/lib64/ceph/mgr/dashboard/controllers/erasure_code_profile.py
/usr/lib64/ceph/mgr/dashboard/controllers/host.py
/usr/lib64/ceph/mgr/dashboard/controllers/monitor.py
/usr/lib64/ceph/mgr/dashboard/controllers/osd.py
/usr/lib64/ceph/mgr/dashboard/controllers/perf_counters.py
/usr/lib64/ceph/mgr/dashboard/controllers/pool.py
/usr/lib64/ceph/mgr/dashboard/controllers/rbd.py
/usr/lib64/ceph/mgr/dashboard/controllers/rbd_mirroring.py
/usr/lib64/ceph/mgr/dashboard/controllers/rgw.py
/usr/lib64/ceph/mgr/dashboard/controllers/summary.py
/usr/lib64/ceph/mgr/dashboard/controllers/task.py
/usr/lib64/ceph/mgr/dashboard/controllers/tcmu_iscsi.py
/usr/lib64/ceph/mgr/dashboard/exceptions.py
/usr/lib64/ceph/mgr/dashboard/frontend/.angular-cli.json
/usr/lib64/ceph/mgr/dashboard/frontend/.editorconfig
/usr/lib64/ceph/mgr/dashboard/frontend/dist/3rdpartylicenses.txt
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/1280px-Mimic_Octopus2.jpg
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/Ceph_Logo_Stacked_RGB_White_120411_fa_256x256.png
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/Ceph_Logo_Standard_RGB_White_120411_fa.png
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/loading.gif
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/logo-mini.png
/usr/lib64/ceph/mgr/dashboard/frontend/dist/assets/notification-icons.png
/usr/lib64/ceph/mgr/dashboard/frontend/dist/favicon.ico
/usr/lib64/ceph/mgr/dashboard/frontend/dist/forkawesome-webfont.421e3082e737096a3376.eot
/usr/lib64/ceph/mgr/dashboard/frontend/dist/forkawesome-webfont.5a5fc1006d9cfbc8b6fc.ttf
/usr/lib64/ceph/mgr/dashboard/frontend/dist/forkawesome-webfont.710e302c1bee9c2b1b56.woff2
/usr/lib64/ceph/mgr/dashboard/frontend/dist/forkawesome-webfont.908a79a7ff22c5c6339a.svg
/usr/lib64/ceph/mgr/dashboard/frontend/dist/forkawesome-webfont.928a48191d521bf0aa72.woff
/usr/lib64/ceph/mgr/dashboard/frontend/dist/glyphicons-halflings-regular.448c34a56d699c29117a.woff2
/usr/lib64/ceph/mgr/dashboard/frontend/dist/glyphicons-halflings-regular.89889688147bd7575d63.svg
/usr/lib64/ceph/mgr/dashboard/frontend/dist/glyphicons-halflings-regular.e18bbf611f2a2e43afc0.ttf
/usr/lib64/ceph/mgr/dashboard/frontend/dist/glyphicons-halflings-regular.f4769f9bdb7466be6508.eot
/usr/lib64/ceph/mgr/dashboard/frontend/dist/glyphicons-halflings-regular.fa2772327f55d8198301.woff
/usr/lib64/ceph/mgr/dashboard/frontend/dist/index.html
/usr/lib64/ceph/mgr/dashboard/frontend/dist/inline.318b50c57b4eba3d437b.bundle.js
/usr/lib64/ceph/mgr/dashboard/frontend/dist/loading.d9e872c7ed736fd8fcb5.gif
/usr/lib64/ceph/mgr/dashboard/frontend/dist/main.dec25924114878c39fd0.bundle.js
/usr/lib64/ceph/mgr/dashboard/frontend/dist/polyfills.6ca0be6b261894835faa.bundle.js
/usr/lib64/ceph/mgr/dashboard/frontend/dist/scripts.8557ea2133c7f8a8e9bc.bundle.js
/usr/lib64/ceph/mgr/dashboard/frontend/dist/styles.7b7345348fb3b1288618.bundle.css
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/cluster/monitors.e2e-spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/cluster/monitors.po.ts
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/cluster/osds.e2e-spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/cluster/osds.po.ts
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/helper.po.ts
/usr/lib64/ceph/mgr/dashboard/frontend/e2e/tsconfig.e2e.json
/usr/lib64/ceph/mgr/dashboard/frontend/karma.conf.js
/usr/lib64/ceph/mgr/dashboard/frontend/package.json
/usr/lib64/ceph/mgr/dashboard/frontend/protractor.conf.js
/usr/lib64/ceph/mgr/dashboard/frontend/proxy.conf.json.sample
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app-routing.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/app.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/block.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/flatten-confirmation-modal/flatten-confimation-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/flatten-confirmation-modal/flatten-confimation-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/flatten-confirmation-modal/flatten-confimation-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/flatten-confirmation-modal/flatten-confimation-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/iscsi/iscsi.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/iscsi/iscsi.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/iscsi/iscsi.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/iscsi/iscsi.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirror-health-color.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirror-health-color.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirroring/mirroring.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirroring/mirroring.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirroring/mirroring.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/mirroring/mirroring.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-details/rbd-details.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-clone-request.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-copy-request.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-create-request.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-edit-request.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-mode.enum.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form-response.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-form.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-form/rbd-parent.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-list/rbd-model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-form/rbd-snapshot-form.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rbd-snapshot-list/rbd-snapshot.model.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rollback-confirmation-modal/rollback-confimation-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rollback-confirmation-modal/rollback-confimation-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rollback-confirmation-modal/rollback-confimation-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/block/rollback-confirmation-modal/rollback-confimation-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/ceph.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-chart/cephfs-chart.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-chart/cephfs-chart.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-chart/cephfs-chart.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-chart/cephfs-chart.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs/cephfs.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs/cephfs.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs/cephfs.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs/cephfs.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/clients/clients.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/clients/clients.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/clients/clients.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cephfs/clients/clients.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/cluster.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/configuration/configuration.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/hosts/hosts.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/monitor/monitor.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/monitor/monitor.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/monitor/monitor.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/monitor/monitor.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard/dashboard.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard/dashboard.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard/dashboard.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/dashboard/dashboard.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health-pie/health-pie.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health-pie/health-pie.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health-pie/health-pie.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health-pie/health-pie.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/health/health.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/log-color.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/log-color.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mds-summary.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mds-summary.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mgr-summary.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mgr-summary.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mon-summary.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/mon-summary.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/osd-summary.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/osd-summary.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/pg-status-style.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/pg-status-style.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/pg-status.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/dashboard/pg-status.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/performance-counter.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/performance-counter/performance-counter.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/performance-counter/performance-counter.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/performance-counter/performance-counter.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/performance-counter/performance-counter.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/table-performance-counter/table-performance-counter.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/table-performance-counter/table-performance-counter.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/table-performance-counter/table-performance-counter.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/performance-counter/table-performance-counter/table-performance-counter.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/pool/pool-list/pool-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/pool/pool.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-user-capability.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-user-s3-key.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-user-subuser.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/models/rgw-user-swift-key.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-501/rgw-501.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-501/rgw-501.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-501/rgw-501.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-501/rgw-501.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-details/rgw-bucket-details.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-form/rgw-bucket-form.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-bucket-list/rgw-bucket-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-details/rgw-daemon-details.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-details/rgw-daemon-details.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-details/rgw-daemon-details.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-details/rgw-daemon-details.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-list/rgw-daemon-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-list/rgw-daemon-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-list/rgw-daemon-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-daemon-list/rgw-daemon-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-capability-modal/rgw-user-capability-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-capability-modal/rgw-user-capability-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-capability-modal/rgw-user-capability-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-capability-modal/rgw-user-capability-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-details/rgw-user-details.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-form/rgw-user-form.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-list/rgw-user-list.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-s3-key-modal/rgw-user-s3-key-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-s3-key-modal/rgw-user-s3-key-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-s3-key-modal/rgw-user-s3-key-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-s3-key-modal/rgw-user-s3-key-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-subuser-modal/rgw-user-subuser-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-subuser-modal/rgw-user-subuser-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-subuser-modal/rgw-user-subuser-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-subuser-modal/rgw-user-subuser-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-swift-key-modal/rgw-user-swift-key-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-swift-key-modal/rgw-user-swift-key-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-swift-key-modal/rgw-user-swift-key-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw-user-swift-key-modal/rgw-user-swift-key-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/ceph/rgw/rgw.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/auth.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/login/login.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/login/login.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/login/login.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/login/login.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/logout/logout.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/logout/logout.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/logout/logout.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/auth/logout/logout.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/core.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/navigation.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/navigation/navigation.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/notifications/notifications.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/task-manager/task-manager.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/task-manager/task-manager.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/task-manager/task-manager.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/navigation/task-manager/task-manager.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/not-found/not-found.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/not-found/not-found.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/not-found/not-found.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/core/not-found/not-found.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/api.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/auth.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/cephfs.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/configuration.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/configuration.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/dashboard.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/dashboard.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/host.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/monitor.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/monitor.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/osd.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/osd.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/pool.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rbd-mirroring.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rbd-mirroring.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rbd.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-bucket.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-daemon.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-daemon.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-user.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/rgw-user.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/table-performance-counter.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/table-performance-counter.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/api/tcmu-iscsi.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/components.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/deletion-modal/deletion-modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/deletion-modal/deletion-modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/deletion-modal/deletion-modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/deletion-modal/deletion-modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/error-panel/error-panel.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/error-panel/error-panel.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/error-panel/error-panel.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/error-panel/error-panel.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/helper/helper.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/info-panel/info-panel.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/info-panel/info-panel.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/info-panel/info-panel.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/info-panel/info-panel.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/loading-panel/loading-panel.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/loading-panel/loading-panel.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/loading-panel/loading-panel.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/loading-panel/loading-panel.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/modal/modal.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/sparkline/sparkline.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/sparkline/sparkline.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/sparkline/sparkline.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/sparkline/sparkline.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/submit-button/submit-button.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/submit-button/submit-button.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/submit-button/submit-button.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/submit-button/submit-button.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/usage-bar/usage-bar.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/view-cache/view-cache.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/view-cache/view-cache.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/view-cache/view-cache.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/components/view-cache/view-cache.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/datatable.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table-key-value/table-key-value.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/datatable/table/table.component.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/autofocus.directive.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/autofocus.directive.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/copy2clipboard-button.directive.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/copy2clipboard-button.directive.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/dimless-binary.directive.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/dimless-binary.directive.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/password-button.directive.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/directives/password-button.directive.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/empty.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/empty.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/enum/cell-template.enum.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/enum/notification-type.enum.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/enum/unix_errno.enum.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/enum/view-cache-status.enum.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/cd-notification.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/cd-table-column.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/cd-table-selection.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/chart-tooltip.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/credentials.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/executing-task.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/finished-task.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/task-exception.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/models/task.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/cd-date.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/cd-date.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/ceph-short-version.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/ceph-short-version.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/dimless-binary.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/dimless.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/dimless.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/filter.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/filter.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/health-color.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/health-color.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/list.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/list.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/pipes.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/relative-date.pipe.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/pipes/relative-date.pipe.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/api-interceptor.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/auth-guard.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/auth-storage.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/formatter.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/formatter.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/module-status-guard.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/notification.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/notification.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/services.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/summary.service.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/summary.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/task-manager-message.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/services/task-manager.service.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/shared.module.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/validators/cd-validators.spec.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/app/shared/validators/cd-validators.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/.gitkeep
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/1280px-Mimic_Octopus2.jpg
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/Ceph_Logo_Stacked_RGB_White_120411_fa_256x256.png
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/Ceph_Logo_Standard_RGB_White_120411_fa.png
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/loading.gif
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/logo-mini.png
/usr/lib64/ceph/mgr/dashboard/frontend/src/assets/notification-icons.png
/usr/lib64/ceph/mgr/dashboard/frontend/src/defaults.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/environments/environment.prod.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/environments/environment.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/favicon.ico
/usr/lib64/ceph/mgr/dashboard/frontend/src/index.html
/usr/lib64/ceph/mgr/dashboard/frontend/src/main.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/openattic-theme.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/polyfills.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/styles.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/styles/chart-tooltip.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/styles/popover.scss
/usr/lib64/ceph/mgr/dashboard/frontend/src/test.ts
/usr/lib64/ceph/mgr/dashboard/frontend/src/tsconfig.app.json
/usr/lib64/ceph/mgr/dashboard/frontend/src/tsconfig.spec.json
/usr/lib64/ceph/mgr/dashboard/frontend/src/typings.d.ts
/usr/lib64/ceph/mgr/dashboard/frontend/tsconfig.json
/usr/lib64/ceph/mgr/dashboard/frontend/tslint.json
/usr/lib64/ceph/mgr/dashboard/module.py
/usr/lib64/ceph/mgr/dashboard/requirements.txt
/usr/lib64/ceph/mgr/dashboard/rest_client.py
/usr/lib64/ceph/mgr/dashboard/run-backend-api-request.sh
/usr/lib64/ceph/mgr/dashboard/run-backend-api-tests.sh
/usr/lib64/ceph/mgr/dashboard/run-frontend-e2e-tests.sh
/usr/lib64/ceph/mgr/dashboard/run-frontend-unittests.sh
/usr/lib64/ceph/mgr/dashboard/run-tox.sh
/usr/lib64/ceph/mgr/dashboard/services/__init__.py
/usr/lib64/ceph/mgr/dashboard/services/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/services/__pycache__/ceph_service.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/services/__pycache__/rgw_client.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/services/ceph_service.py
/usr/lib64/ceph/mgr/dashboard/services/rgw_client.py
/usr/lib64/ceph/mgr/dashboard/settings.py
/usr/lib64/ceph/mgr/dashboard/tests/__init__.py
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/helper.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_notification.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_rbd_mirroring.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_rest_tasks.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_settings.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_task.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_tcmu_iscsi.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/__pycache__/test_tools.cpython-36.pyc
/usr/lib64/ceph/mgr/dashboard/tests/helper.py
/usr/lib64/ceph/mgr/dashboard/tests/test_notification.py
/usr/lib64/ceph/mgr/dashboard/tests/test_rbd_mirroring.py
/usr/lib64/ceph/mgr/dashboard/tests/test_rest_tasks.py
/usr/lib64/ceph/mgr/dashboard/tests/test_settings.py
/usr/lib64/ceph/mgr/dashboard/tests/test_task.py
/usr/lib64/ceph/mgr/dashboard/tests/test_tcmu_iscsi.py
/usr/lib64/ceph/mgr/dashboard/tests/test_tools.py
/usr/lib64/ceph/mgr/dashboard/tools.py
/usr/lib64/ceph/mgr/dashboard/tox.ini
/usr/lib64/ceph/mgr/hello/__init__.py
/usr/lib64/ceph/mgr/hello/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/hello/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/hello/module.py
/usr/lib64/ceph/mgr/influx/__init__.py
/usr/lib64/ceph/mgr/influx/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/influx/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/influx/module.py
/usr/lib64/ceph/mgr/iostat/__init__.py
/usr/lib64/ceph/mgr/iostat/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/iostat/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/iostat/module.py
/usr/lib64/ceph/mgr/localpool/__init__.py
/usr/lib64/ceph/mgr/localpool/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/localpool/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/localpool/module.py
/usr/lib64/ceph/mgr/mgr_module.py
/usr/lib64/ceph/mgr/prometheus/__init__.py
/usr/lib64/ceph/mgr/prometheus/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/prometheus/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/prometheus/module.py
/usr/lib64/ceph/mgr/restful/__init__.py
/usr/lib64/ceph/mgr/restful/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/__pycache__/common.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/__pycache__/context.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/__pycache__/decorators.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/__pycache__/hooks.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__init__.py
/usr/lib64/ceph/mgr/restful/api/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/config.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/crush.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/doc.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/mon.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/osd.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/pool.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/request.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/__pycache__/server.cpython-36.pyc
/usr/lib64/ceph/mgr/restful/api/config.py
/usr/lib64/ceph/mgr/restful/api/crush.py
/usr/lib64/ceph/mgr/restful/api/doc.py
/usr/lib64/ceph/mgr/restful/api/mon.py
/usr/lib64/ceph/mgr/restful/api/osd.py
/usr/lib64/ceph/mgr/restful/api/pool.py
/usr/lib64/ceph/mgr/restful/api/request.py
/usr/lib64/ceph/mgr/restful/api/server.py
/usr/lib64/ceph/mgr/restful/common.py
/usr/lib64/ceph/mgr/restful/context.py
/usr/lib64/ceph/mgr/restful/decorators.py
/usr/lib64/ceph/mgr/restful/hooks.py
/usr/lib64/ceph/mgr/restful/module.py
/usr/lib64/ceph/mgr/selftest/__init__.py
/usr/lib64/ceph/mgr/selftest/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/selftest/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/selftest/module.py
/usr/lib64/ceph/mgr/smart/__init__.py
/usr/lib64/ceph/mgr/smart/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/smart/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/smart/module.py
/usr/lib64/ceph/mgr/status/__init__.py
/usr/lib64/ceph/mgr/status/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/status/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/status/module.py
/usr/lib64/ceph/mgr/telegraf/__init__.py
/usr/lib64/ceph/mgr/telegraf/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/telegraf/__pycache__/basesocket.cpython-36.pyc
/usr/lib64/ceph/mgr/telegraf/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/telegraf/__pycache__/protocol.cpython-36.pyc
/usr/lib64/ceph/mgr/telegraf/__pycache__/utils.cpython-36.pyc
/usr/lib64/ceph/mgr/telegraf/basesocket.py
/usr/lib64/ceph/mgr/telegraf/module.py
/usr/lib64/ceph/mgr/telegraf/protocol.py
/usr/lib64/ceph/mgr/telegraf/utils.py
/usr/lib64/ceph/mgr/telemetry/__init__.py
/usr/lib64/ceph/mgr/telemetry/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/telemetry/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/telemetry/module.py
/usr/lib64/ceph/mgr/zabbix/__init__.py
/usr/lib64/ceph/mgr/zabbix/__pycache__/__init__.cpython-36.pyc
/usr/lib64/ceph/mgr/zabbix/__pycache__/module.cpython-36.pyc
/usr/lib64/ceph/mgr/zabbix/module.py
/usr/lib64/ceph/mgr/zabbix/zabbix_template.xml

%files bin
%defattr(-,root,root,-)
/usr/bin/ceph
/usr/bin/ceph-authtool
/usr/bin/ceph-bluestore-tool
/usr/bin/ceph-clsinfo
/usr/bin/ceph-conf
/usr/bin/ceph-create-keys
/usr/bin/ceph-dencoder
/usr/bin/ceph-detect-init
/usr/bin/ceph-disk
/usr/bin/ceph-kvstore-tool
/usr/bin/ceph-mds
/usr/bin/ceph-mgr
/usr/bin/ceph-mon
/usr/bin/ceph-monstore-tool
/usr/bin/ceph-objectstore-tool
/usr/bin/ceph-osd
/usr/bin/ceph-osdomap-tool
/usr/bin/ceph-post-file
/usr/bin/ceph-rbdnamer
/usr/bin/ceph-run
/usr/bin/ceph-syn
/usr/bin/ceph-volume
/usr/bin/ceph-volume-systemd
/usr/bin/cephfs-data-scan
/usr/bin/cephfs-journal-tool
/usr/bin/cephfs-table-tool
/usr/bin/crushtool
/usr/bin/librados-config
/usr/bin/monmaptool
/usr/bin/mount.ceph
/usr/bin/osdmaptool
/usr/bin/rados
/usr/bin/radosgw
/usr/bin/radosgw-admin
/usr/bin/radosgw-es
/usr/bin/radosgw-object-expirer
/usr/bin/radosgw-token
/usr/bin/rbd
/usr/bin/rbd-mirror
/usr/bin/rbd-nbd
/usr/bin/rbd-replay
/usr/bin/rbd-replay-many
/usr/bin/rbd-replay-prep
/usr/bin/rbdmap
/usr/libexec/ceph/ceph-osd-prestart.sh
/usr/libexec/ceph/ceph_common.sh

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/ceph-disk@.service
/usr/lib/systemd/system/ceph-mds.target
/usr/lib/systemd/system/ceph-mds@.service
/usr/lib/systemd/system/ceph-mon.target
/usr/lib/systemd/system/ceph-mon@.service
/usr/lib/systemd/system/ceph-osd.target
/usr/lib/systemd/system/ceph-osd@.service
/usr/lib/systemd/system/ceph-radosgw.target
/usr/lib/systemd/system/ceph-radosgw@.service
/usr/lib/systemd/system/ceph-rbd-mirror.target
/usr/lib/systemd/system/ceph-rbd-mirror@.service
/usr/lib/systemd/system/ceph-volume@.service
/usr/lib/systemd/system/ceph.target
/usr/lib/systemd/system/rbdmap.service
/usr/lib/tmpfiles.d/ceph.conf
/usr/lib/udev/rules.d/50-rbd.rules
/usr/lib/udev/rules.d/60-ceph-by-parttypeuuid.rules
/usr/lib/udev/rules.d/95-ceph-osd.rules

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/ceph
/usr/share/bash-completion/completions/rados
/usr/share/bash-completion/completions/radosgw-admin
/usr/share/bash-completion/completions/rbd
/usr/share/ceph/id_rsa_drop.ceph.com
/usr/share/ceph/id_rsa_drop.ceph.com.pub
/usr/share/ceph/known_hosts_drop.ceph.com
/usr/share/defaults/sudo/sudoers.d/ceph

%files dev
%defattr(-,root,root,-)
/usr/include/cephfs/ceph_statx.h
/usr/include/cephfs/libcephfs.h
/usr/include/rados/buffer.h
/usr/include/rados/buffer_fwd.h
/usr/include/rados/crc32c.h
/usr/include/rados/inline_memory.h
/usr/include/rados/librados.h
/usr/include/rados/librados.hpp
/usr/include/rados/librgw.h
/usr/include/rados/memory.h
/usr/include/rados/objclass.h
/usr/include/rados/page.h
/usr/include/rados/rados_types.h
/usr/include/rados/rados_types.hpp
/usr/include/rados/rgw_file.h
/usr/include/radosstriper/libradosstriper.h
/usr/include/radosstriper/libradosstriper.hpp
/usr/include/rbd/features.h
/usr/include/rbd/librbd.h
/usr/include/rbd/librbd.hpp
/usr/lib64/libcephfs.so
/usr/lib64/librados.so
/usr/lib64/libradosstriper.so
/usr/lib64/librbd.so
/usr/lib64/librgw.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ceph/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/ceph/compressor/libceph_lz4.so
/usr/lib64/ceph/compressor/libceph_lz4.so.2
/usr/lib64/ceph/compressor/libceph_lz4.so.2.0.0
/usr/lib64/ceph/compressor/libceph_snappy.so
/usr/lib64/ceph/compressor/libceph_snappy.so.2
/usr/lib64/ceph/compressor/libceph_snappy.so.2.0.0
/usr/lib64/ceph/compressor/libceph_zlib.so
/usr/lib64/ceph/compressor/libceph_zlib.so.2
/usr/lib64/ceph/compressor/libceph_zlib.so.2.0.0
/usr/lib64/ceph/compressor/libceph_zstd.so
/usr/lib64/ceph/compressor/libceph_zstd.so.2
/usr/lib64/ceph/compressor/libceph_zstd.so.2.0.0
/usr/lib64/ceph/crypto/libceph_crypto_isal.so
/usr/lib64/ceph/crypto/libceph_crypto_isal.so.1
/usr/lib64/ceph/crypto/libceph_crypto_isal.so.1.0.0
/usr/lib64/ceph/erasure-code/libec_isa.so
/usr/lib64/ceph/erasure-code/libec_jerasure.so
/usr/lib64/ceph/erasure-code/libec_jerasure_generic.so
/usr/lib64/ceph/erasure-code/libec_jerasure_sse3.so
/usr/lib64/ceph/erasure-code/libec_jerasure_sse4.so
/usr/lib64/ceph/erasure-code/libec_lrc.so
/usr/lib64/ceph/erasure-code/libec_shec.so
/usr/lib64/ceph/erasure-code/libec_shec_generic.so
/usr/lib64/ceph/erasure-code/libec_shec_sse3.so
/usr/lib64/ceph/erasure-code/libec_shec_sse4.so
/usr/lib64/ceph/libceph-common.so
/usr/lib64/ceph/libceph-common.so.0
/usr/lib64/libcephfs.so.2
/usr/lib64/libcephfs.so.2.0.0
/usr/lib64/librados.so.2
/usr/lib64/librados.so.2.0.0
/usr/lib64/libradosstriper.so.1
/usr/lib64/libradosstriper.so.1.0.0
/usr/lib64/librbd.so.1
/usr/lib64/librbd.so.1.12.0
/usr/lib64/librgw.so.2
/usr/lib64/librgw.so.2.0.0
/usr/lib64/rados-classes/libcls_cephfs.so
/usr/lib64/rados-classes/libcls_cephfs.so.1
/usr/lib64/rados-classes/libcls_cephfs.so.1.0.0
/usr/lib64/rados-classes/libcls_hello.so
/usr/lib64/rados-classes/libcls_hello.so.1
/usr/lib64/rados-classes/libcls_hello.so.1.0.0
/usr/lib64/rados-classes/libcls_journal.so
/usr/lib64/rados-classes/libcls_journal.so.1
/usr/lib64/rados-classes/libcls_journal.so.1.0.0
/usr/lib64/rados-classes/libcls_kvs.so
/usr/lib64/rados-classes/libcls_kvs.so.1
/usr/lib64/rados-classes/libcls_kvs.so.1.0.0
/usr/lib64/rados-classes/libcls_lock.so
/usr/lib64/rados-classes/libcls_lock.so.1
/usr/lib64/rados-classes/libcls_lock.so.1.0.0
/usr/lib64/rados-classes/libcls_log.so
/usr/lib64/rados-classes/libcls_log.so.1
/usr/lib64/rados-classes/libcls_log.so.1.0.0
/usr/lib64/rados-classes/libcls_lua.so
/usr/lib64/rados-classes/libcls_lua.so.1
/usr/lib64/rados-classes/libcls_lua.so.1.0.0
/usr/lib64/rados-classes/libcls_numops.so
/usr/lib64/rados-classes/libcls_numops.so.1
/usr/lib64/rados-classes/libcls_numops.so.1.0.0
/usr/lib64/rados-classes/libcls_otp.so
/usr/lib64/rados-classes/libcls_otp.so.1
/usr/lib64/rados-classes/libcls_otp.so.1.0.0
/usr/lib64/rados-classes/libcls_rbd.so
/usr/lib64/rados-classes/libcls_rbd.so.1
/usr/lib64/rados-classes/libcls_rbd.so.1.0.0
/usr/lib64/rados-classes/libcls_refcount.so
/usr/lib64/rados-classes/libcls_refcount.so.1
/usr/lib64/rados-classes/libcls_refcount.so.1.0.0
/usr/lib64/rados-classes/libcls_replica_log.so
/usr/lib64/rados-classes/libcls_replica_log.so.1
/usr/lib64/rados-classes/libcls_replica_log.so.1.0.0
/usr/lib64/rados-classes/libcls_rgw.so
/usr/lib64/rados-classes/libcls_rgw.so.1
/usr/lib64/rados-classes/libcls_rgw.so.1.0.0
/usr/lib64/rados-classes/libcls_sdk.so
/usr/lib64/rados-classes/libcls_sdk.so.1
/usr/lib64/rados-classes/libcls_sdk.so.1.0.0
/usr/lib64/rados-classes/libcls_statelog.so
/usr/lib64/rados-classes/libcls_statelog.so.1
/usr/lib64/rados-classes/libcls_statelog.so.1.0.0
/usr/lib64/rados-classes/libcls_timeindex.so
/usr/lib64/rados-classes/libcls_timeindex.so.1
/usr/lib64/rados-classes/libcls_timeindex.so.1.0.0
/usr/lib64/rados-classes/libcls_user.so
/usr/lib64/rados-classes/libcls_user.so.1
/usr/lib64/rados-classes/libcls_user.so.1.0.0
/usr/lib64/rados-classes/libcls_version.so
/usr/lib64/rados-classes/libcls_version.so.1
/usr/lib64/rados-classes/libcls_version.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/ceph/COPYING-GPL2
/usr/share/doc/ceph/COPYING-LGPL2.1
/usr/share/doc/ceph/src_blkin_COPYRIGHT
/usr/share/doc/ceph/src_boost_LICENSE_1_0.txt
/usr/share/doc/ceph/src_boost_libs_beast_LICENSE_1_0.txt
/usr/share/doc/ceph/src_boost_libs_beast_test_bench_parser_nodejs-parser_LICENSE-MIT
/usr/share/doc/ceph/src_boost_libs_beast_test_extern_zlib-1.2.11_contrib_dotzlib_LICENSE_1_0.txt
/usr/share/doc/ceph/src_boost_libs_callable_traits_LICENSE.md
/usr/share/doc/ceph/src_boost_libs_compute_LICENSE_1_0.txt
/usr/share/doc/ceph/src_boost_libs_date_time_xmldoc_license.xml
/usr/share/doc/ceph/src_boost_libs_hana_LICENSE.md
/usr/share/doc/ceph/src_boost_libs_hof_LICENSE.md
/usr/share/doc/ceph/src_boost_libs_python_LICENSE_1_0.txt
/usr/share/doc/ceph/src_boost_tools_boostbook_xsl_caramel_LICENSE
/usr/share/doc/ceph/src_civetweb_LICENSE.md
/usr/share/doc/ceph/src_civetweb_src_third_party_duktape-1.5.2_LICENSE.txt
/usr/share/doc/ceph/src_civetweb_src_third_party_duktape-1.8.0_LICENSE.txt
/usr/share/doc/ceph/src_civetweb_src_third_party_lua-5.1.5_COPYRIGHT
/usr/share/doc/ceph/src_crypto_isa-l_isa-l_crypto_LICENSE
/usr/share/doc/ceph/src_dmclock_COPYING
/usr/share/doc/ceph/src_dmclock_COPYING-LGPL2.1
/usr/share/doc/ceph/src_erasure-code_jerasure_gf-complete_COPYING
/usr/share/doc/ceph/src_erasure-code_jerasure_jerasure_COPYING
/usr/share/doc/ceph/src_googletest_googlemock_LICENSE
/usr/share/doc/ceph/src_googletest_googlemock_scripts_generator_LICENSE
/usr/share/doc/ceph/src_googletest_googletest_LICENSE
/usr/share/doc/ceph/src_isa-l_LICENSE
/usr/share/doc/ceph/src_rapidjson_bin_jsonschema_LICENSE
/usr/share/doc/ceph/src_rapidjson_license.txt
/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googlemock_LICENSE
/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googlemock_scripts_generator_LICENSE
/usr/share/doc/ceph/src_rapidjson_thirdparty_gtest_googletest_LICENSE
/usr/share/doc/ceph/src_rocksdb_COPYING
/usr/share/doc/ceph/src_rocksdb_LICENSE.Apache
/usr/share/doc/ceph/src_rocksdb_LICENSE.leveldb
/usr/share/doc/ceph/src_rocksdb_docs_LICENSE-DOCUMENTATION
/usr/share/doc/ceph/src_spdk_LICENSE
/usr/share/doc/ceph/src_spdk_dpdk_LICENSE.GPL
/usr/share/doc/ceph/src_spdk_dpdk_LICENSE.LGPL
/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_bnx2x_LICENSE.bnx2x_pmd
/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_enic_LICENSE
/usr/share/doc/ceph/src_spdk_dpdk_drivers_net_qede_LICENSE.qede_pmd
/usr/share/doc/ceph/src_xxHash_LICENSE
/usr/share/doc/ceph/src_zstd_COPYING
/usr/share/doc/ceph/src_zstd_LICENSE
/usr/share/doc/ceph/src_zstd_contrib_linux-kernel_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/ceph-authtool.8
/usr/share/man/man8/ceph-bluestore-tool.8
/usr/share/man/man8/ceph-clsinfo.8
/usr/share/man/man8/ceph-conf.8
/usr/share/man/man8/ceph-create-keys.8
/usr/share/man/man8/ceph-dencoder.8
/usr/share/man/man8/ceph-deploy.8
/usr/share/man/man8/ceph-detect-init.8
/usr/share/man/man8/ceph-disk.8
/usr/share/man/man8/ceph-kvstore-tool.8
/usr/share/man/man8/ceph-mds.8
/usr/share/man/man8/ceph-mon.8
/usr/share/man/man8/ceph-osd.8
/usr/share/man/man8/ceph-post-file.8
/usr/share/man/man8/ceph-rbdnamer.8
/usr/share/man/man8/ceph-run.8
/usr/share/man/man8/ceph-syn.8
/usr/share/man/man8/ceph-volume-systemd.8
/usr/share/man/man8/ceph-volume.8
/usr/share/man/man8/ceph.8
/usr/share/man/man8/crushtool.8
/usr/share/man/man8/librados-config.8
/usr/share/man/man8/monmaptool.8
/usr/share/man/man8/mount.ceph.8
/usr/share/man/man8/osdmaptool.8
/usr/share/man/man8/rados.8
/usr/share/man/man8/radosgw-admin.8
/usr/share/man/man8/radosgw.8
/usr/share/man/man8/rbd-mirror.8
/usr/share/man/man8/rbd-nbd.8
/usr/share/man/man8/rbd-replay-many.8
/usr/share/man/man8/rbd-replay-prep.8
/usr/share/man/man8/rbd-replay.8
/usr/share/man/man8/rbd.8
/usr/share/man/man8/rbdmap.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
